version: '3.8'

services:

  app:
    build:
      context: . 
    image: examen-app:latest  
    container_name: examen_app_container
    ports:
      - "8080:8080"  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/examenesdb 
      - SPRING_DATASOURCE_USERNAME=root  
      - SPRING_DATASOURCE_PASSWORD=root  
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  
      - SPRING_JPA_SHOW_SQL=true  
    depends_on:
      - db  

 
  db:
    image: mysql:8.0 
    container_name: examen_db_container 
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: examenesdb  
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql  

# Volúmenes persistentes
volumes:
  db_data:
    driver: local  
